/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:bc6c8a10-0622-4975-868c-f235565422c1",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_r3h5Li3m2",
    "aws_user_pools_web_client_id": "7a2121f37bj29sn7gnlcmahoc0",
    "oauth": {}
};


export default awsmobile;
